# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OdJVCtX3Cvc-fYoMdyAITAyFaYttyuAV
"""

# -*- coding: utf-8 -*-
import streamlit as st
import pandas as pd
import numpy as np
import re
import io
from openpyxl import load_workbook
from openpyxl.styles import (
    PatternFill, Font, Alignment, Border, Side, GradientFill
)
from openpyxl.utils import get_column_letter
from openpyxl.formatting.rule import ColorScaleRule, DataBarRule

# ReportLab — PDF oluşturma
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors as rl_colors
from reportlab.lib.units import cm, mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether, PageBreak
)
from reportlab.graphics.shapes import Drawing, Rect, String, Line, Group
from reportlab.graphics import renderPDF
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

# ── Ek importlar ────────────────────────────────────────────────────────────
import hashlib
import urllib.request
import os

# ── Sayfa ayarları ──────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Optik Notlandırma",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── CSS ─────────────────────────────────────────────────────────────────────
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap');

/* ══ CSS DEĞIŞKENLERI — DARK (varsayılan) ══ */
:root {
    --bg:          #0d0d14;
    --bg2:         #12111c;
    --bg3:         #1a1927;
    --border:      #1e1d2e;
    --border2:     #2a2840;
    --text:        #e2e0f0;
    --text2:       #a09eb8;
    --text3:       #6b6880;
    --text4:       #4a4860;
    --sidebar-bg1: #12111c;
    --sidebar-bg2: #0f0f1a;
    --hero-bg1:    #13111f;
    --hero-bg2:    #0f1520;
    --input-bg:    #12111c;
    --input-text:  #e2e0f0;
    --bar-bg:      #1a1927;
    --card-info-bg:#12111c;
    --mc-val:      #ffffff;
    --dist-fill:   rgba(255,255,255,0.9);
}

/* ══ LIGHT MODE — sistem tercihine göre ══ */
@media (prefers-color-scheme: light) {
    :root {
        --bg:          #f5f4ff;
        --bg2:         #ffffff;
        --bg3:         #ededf8;
        --border:      #dddaf0;
        --border2:     #c8c4e8;
        --text:        #1a1835;
        --text2:       #4a4770;
        --text3:       #7a789a;
        --text4:       #a0a0b8;
        --sidebar-bg1: #f0effe;
        --sidebar-bg2: #ebe9fc;
        --hero-bg1:    #eeeaff;
        --hero-bg2:    #e8f0ff;
        --input-bg:    #ffffff;
        --input-text:  #1a1835;
        --bar-bg:      #e8e6f8;
        --card-info-bg:#ffffff;
        --mc-val:      #1a1835;
        --dist-fill:   rgba(0,0,0,0.75);
    }
}

html, body, [class*="css"] { font-family: 'Inter', sans-serif; }

.stApp {
    background: var(--bg) !important;
    color: var(--text) !important;
}

[data-testid="stSidebar"] {
    background: linear-gradient(180deg, var(--sidebar-bg1) 0%, var(--sidebar-bg2) 100%) !important;
    border-right: 1px solid var(--border) !important;
}

/* Hero */
.hero-wrap {
    background: linear-gradient(135deg, var(--hero-bg1) 0%, var(--hero-bg2) 100%);
    border: 1px solid var(--border);
    border-radius: 16px;
    padding: 2.2rem 2.5rem;
    margin-bottom: 1.8rem;
    position: relative;
    overflow: hidden;
}
.hero-wrap::before {
    content: '';
    position: absolute;
    top: -60px; right: -60px;
    width: 220px; height: 220px;
    background: radial-gradient(circle, rgba(124,106,247,0.18) 0%, transparent 70%);
    pointer-events: none;
}
.hero-title {
    font-size: 2.0rem;
    font-weight: 700;
    letter-spacing: -0.04em;
    color: var(--text);
    margin: 0;
    line-height: 1.1;
}
.hero-title span { color: #7c6af7; }
.hero-sub {
    color: var(--text3);
    font-size: 0.9rem;
    margin-top: 0.4rem;
    font-weight: 400;
}
.hero-credit {
    display: inline-flex;
    align-items: center;
    gap: 0.45rem;
    margin-top: 1.1rem;
    background: rgba(124,106,247,0.09);
    border: 1px solid rgba(124,106,247,0.22);
    border-radius: 999px;
    padding: 0.28rem 0.9rem;
    font-size: 0.75rem;
    color: var(--text);
    font-weight: 500;
    letter-spacing: 0.01em;
}
.hero-credit b { color: var(--text); font-weight: 700; }
.hero-badge {
    display: inline-block;
    background: rgba(124,106,247,0.13);
    border: 1px solid rgba(124,106,247,0.28);
    color: #a89ef9;
    border-radius: 999px;
    padding: 0.18rem 0.75rem;
    font-size: 0.72rem;
    font-weight: 600;
    letter-spacing: 0.06em;
    text-transform: uppercase;
    margin-bottom: 0.7rem;
    font-family: 'JetBrains Mono', monospace;
}

/* Metric grid */
.metric-grid {
    display: grid;
    grid-template-columns: repeat(5, 1fr);
    gap: 0.9rem;
    margin: 1.4rem 0;
}
.mc {
    background: var(--bg2);
    border: 1px solid var(--border);
    border-radius: 12px;
    padding: 1.1rem 1.3rem;
    position: relative;
    overflow: hidden;
}
.mc::after {
    content: '';
    position: absolute;
    bottom: 0; left: 0; right: 0;
    height: 2px;
}
.mc.purple::after { background: linear-gradient(90deg, #7c6af7, #a89ef9); }
.mc.green::after  { background: linear-gradient(90deg, #34d399, #6ee7b7); }
.mc.amber::after  { background: linear-gradient(90deg, #f59e0b, #fbbf24); }
.mc.rose::after   { background: linear-gradient(90deg, #f43f5e, #fb7185); }
.mc.sky::after    { background: linear-gradient(90deg, #0ea5e9, #38bdf8); }
.mc-label { font-size: 0.7rem; color: var(--text3); text-transform: uppercase; letter-spacing: 0.09em; font-weight: 600; }
.mc-val   { font-family: 'JetBrains Mono', monospace; font-size: 1.9rem; font-weight: 500; color: var(--mc-val); margin-top: 0.15rem; line-height: 1; }
.mc-sub   { font-size: 0.72rem; color: var(--text4); margin-top: 0.25rem; }

/* Section headers */
.sec-head {
    font-size: 0.78rem;
    font-weight: 600;
    letter-spacing: 0.1em;
    text-transform: uppercase;
    color: var(--text3);
    margin: 1.8rem 0 0.8rem 0;
    display: flex;
    align-items: center;
    gap: 0.5rem;
}
.sec-head::after {
    content: '';
    flex: 1;
    height: 1px;
    background: var(--border);
}

/* Soru analizi kartları */
.qa-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(72px, 1fr));
    gap: 0.55rem;
    margin: 0.8rem 0;
}
.qa-card {
    background: var(--bg2);
    border: 1px solid var(--border);
    border-radius: 10px;
    padding: 0.65rem 0.5rem;
    text-align: center;
}
.qa-card .q-no  { font-size: 0.65rem; color: var(--text3); font-weight: 600; text-transform: uppercase; letter-spacing: 0.06em; }
.qa-card .q-pct { font-family: 'JetBrains Mono', monospace; font-size: 1.1rem; font-weight: 600; margin-top: 0.1rem; }
.qa-card .q-ans { font-size: 0.7rem; color: var(--text3); margin-top: 0.15rem; }
.qa-card.easy   { border-color: rgba(52,211,153,0.4); }
.qa-card.easy .q-pct { color: #34d399; }
.qa-card.mid    { border-color: rgba(251,191,36,0.3); }
.qa-card.mid .q-pct  { color: #f59e0b; }
.qa-card.hard   { border-color: rgba(248,113,113,0.4); }
.qa-card.hard .q-pct { color: #f87171; }

/* Sidebar steps */
.step-lbl {
    font-size: 0.68rem;
    font-weight: 700;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    color: #7c6af7;
    margin-bottom: 0.4rem;
    font-family: 'JetBrains Mono', monospace;
}

/* Warn/ok boxes */
.warn-box {
    background: rgba(251,191,36,0.08);
    border-left: 3px solid #fbbf24;
    padding: 0.6rem 1rem;
    border-radius: 0 8px 8px 0;
    font-size: 0.82rem;
    color: #d97706;
    margin: 0.25rem 0;
    font-family: 'JetBrains Mono', monospace;
}
.ok-box {
    background: rgba(52,211,153,0.08);
    border-left: 3px solid #34d399;
    padding: 0.7rem 1.1rem;
    border-radius: 0 8px 8px 0;
    font-size: 0.85rem;
    color: #059669;
    margin: 0.5rem 0;
}

/* Footer */
.footer-bar {
    margin-top: 3rem;
    padding: 1.2rem 0 0.5rem 0;
    border-top: 1px solid var(--border);
    text-align: center;
    font-size: 0.75rem;
    color: var(--text4);
    line-height: 1.8;
}
.footer-bar b { color: var(--text3); font-weight: 600; }
.footer-bar a { color: #7c6af7; text-decoration: none; }

/* Butonlar */
.stButton > button {
    background: linear-gradient(135deg, #7c6af7, #6b59e8) !important;
    color: white !important;
    border: none !important;
    border-radius: 9px !important;
    font-family: 'Inter', sans-serif !important;
    font-weight: 600 !important;
    font-size: 0.92rem !important;
    padding: 0.65rem 1.8rem !important;
    transition: all 0.2s !important;
    letter-spacing: -0.01em !important;
}
.stButton > button:hover {
    background: linear-gradient(135deg, #8b79f8, #7c6af7) !important;
    transform: translateY(-1px);
    box-shadow: 0 4px 20px rgba(124,106,247,0.3) !important;
}
[data-testid="stDownloadButton"]:nth-of-type(1) > button {
    background: rgba(52,211,153,0.1) !important;
    border: 1px solid rgba(52,211,153,0.4) !important;
    color: #059669 !important;
    border-radius: 9px !important;
    font-family: 'Inter', sans-serif !important;
    font-weight: 600 !important;
    letter-spacing: -0.01em !important;
}
[data-testid="stDownloadButton"]:nth-of-type(1) > button:hover {
    background: rgba(52,211,153,0.18) !important;
    box-shadow: 0 4px 16px rgba(52,211,153,0.2) !important;
}
[data-testid="stDownloadButton"]:nth-of-type(2) > button {
    background: rgba(239,68,68,0.08) !important;
    border: 1px solid rgba(239,68,68,0.35) !important;
    color: #ef4444 !important;
    border-radius: 9px !important;
    font-family: 'Inter', sans-serif !important;
    font-weight: 600 !important;
    letter-spacing: -0.01em !important;
}
[data-testid="stDownloadButton"]:nth-of-type(2) > button:hover {
    background: rgba(239,68,68,0.16) !important;
    box-shadow: 0 4px 16px rgba(239,68,68,0.2) !important;
}
.stTextInput > div > div > input {
    background: var(--input-bg) !important;
    border: 1px solid var(--border) !important;
    color: var(--input-text) !important;
    font-family: 'JetBrains Mono', monospace !important;
    border-radius: 8px !important;
    font-size: 1rem !important;
    letter-spacing: 0.08em !important;
}
.stTextInput > div > div > input:focus {
    border-color: #7c6af7 !important;
    box-shadow: 0 0 0 2px rgba(124,106,247,0.2) !important;
}

/* Dağılım bar */
.dist-bar-wrap { margin: 1rem 0; }
.dist-row { display: flex; align-items: center; gap: 0.7rem; margin: 0.3rem 0; }
.dist-lbl { font-size: 0.75rem; color: var(--text3); width: 70px; text-align: right; font-family: 'JetBrains Mono', monospace; }
.dist-bar-bg { flex: 1; background: var(--bar-bg); border-radius: 4px; height: 20px; overflow: hidden; }
.dist-bar-fill { height: 100%; border-radius: 4px; display: flex; align-items: center; padding-left: 8px; }
.dist-bar-fill span { font-size: 0.7rem; font-weight: 600; color: var(--dist-fill); font-family: 'JetBrains Mono', monospace; }
.dist-cnt { font-size: 0.73rem; color: var(--text3); width: 30px; }

hr { border-color: var(--border) !important; }

/* Login ekranı */
.login-wrap {
    max-width: 420px;
    margin: 4rem auto;
    background: var(--bg2);
    border: 1px solid var(--border);
    border-radius: 18px;
    padding: 2.8rem 2.4rem;
    position: relative;
    overflow: hidden;
}
.login-wrap::before {
    content: '';
    position: absolute;
    top: -80px; right: -80px;
    width: 260px; height: 260px;
    background: radial-gradient(circle, rgba(124,106,247,0.15) 0%, transparent 70%);
    pointer-events: none;
}
.login-logo {
    font-size: 2.8rem;
    text-align: center;
    margin-bottom: 0.5rem;
}
.login-title {
    font-size: 1.3rem;
    font-weight: 700;
    letter-spacing: -0.03em;
    color: var(--text);
    text-align: center;
    margin-bottom: 0.3rem;
}
.login-sub {
    font-size: 0.82rem;
    color: var(--text3);
    text-align: center;
    margin-bottom: 1.8rem;
}
.ders-card {
    background: var(--bg2);
    border: 1px solid var(--border);
    border-radius: 12px;
    padding: 1.3rem 1.5rem;
    margin-bottom: 1.2rem;
}
.ders-card-title {
    font-size: 0.7rem;
    font-weight: 700;
    letter-spacing: 0.1em;
    text-transform: uppercase;
    color: var(--text3);
    margin-bottom: 0.9rem;
}
.kilavuz-wrap {
    background: var(--bg2);
    border: 1px solid var(--border);
    border-radius: 14px;
    padding: 2rem;
}
.kilavuz-step {
    display: flex;
    gap: 1rem;
    margin-bottom: 1.4rem;
    align-items: flex-start;
}
.kilavuz-num {
    background: rgba(124,106,247,0.15);
    border: 1px solid rgba(124,106,247,0.3);
    color: #7c6af7;
    font-family: 'JetBrains Mono', monospace;
    font-size: 0.85rem;
    font-weight: 700;
    width: 32px;
    height: 32px;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
}
.kilavuz-content {
    flex: 1;
}
.kilavuz-content b {
    color: var(--text);
    display: block;
    margin-bottom: 0.3rem;
    font-size: 0.92rem;
}
.kilavuz-content p {
    color: var(--text3);
    font-size: 0.82rem;
    line-height: 1.7;
    margin: 0;
}
.kilavuz-code {
    background: var(--bg3);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 0.7rem 1rem;
    font-family: 'JetBrains Mono', monospace;
    font-size: 0.78rem;
    color: #7c6af7;
    margin-top: 0.5rem;
    line-height: 1.9;
}

/* Streamlit varsayılan arka planları sıfırla */
[data-testid="stVerticalBlock"],
[data-testid="stHorizontalBlock"],
[data-testid="column"],
[data-testid="stColumn"],
[data-testid="block-container"],
.element-container,
.stMarkdown,
section[data-testid="stSidebar"] > div,
div[data-testid="stDecoration"] { background: transparent !important; }

[data-testid="stDecoration"] { display: none !important; }

header[data-testid="stHeader"] {
    background: transparent !important;
    border-bottom: none !important;
}
</style>
""", unsafe_allow_html=True)


# ══════════════════════════════════════════════════════════════════════════════
# CORE FONKSİYONLAR
# ══════════════════════════════════════════════════════════════════════════════

def satir_parse_et(satir):
    satir = satir.strip()
    if not satir:
        return None, None
    blok_match = re.search(r'(C?\d{8,30})', satir, re.IGNORECASE)
    if not blok_match:
        return None, f"Sayısal blok bulunamadı → {satir[:60]}"
    ad_soyad = satir[:blok_match.start()].strip()
    if not ad_soyad:
        return None, "Ad Soyad boş"
    blok     = blok_match.group(1)
    blok_end = blok_match.end()
    cap      = blok.upper().startswith('C')
    rakamlar = blok[1:] if cap else blok
    tc = ""; ogr_no = ""; cep = ""
    if len(rakamlar) >= 19:
        tc           = rakamlar[:11]
        ogr_no_rakam = rakamlar[11:19]
        kalan_rakam  = rakamlar[19:]
        if re.match(r'^(05\d{9}|5\d{9})$', kalan_rakam):
            cep = kalan_rakam if kalan_rakam.startswith('0') else '0' + kalan_rakam
        ogr_no = ('C' if cap else '') + ogr_no_rakam
    elif len(rakamlar) == 11:
        tc = rakamlar
        kalan_sonra = satir[blok_end:].strip()
        ogr_match = re.match(r'^(C?\d{8})', kalan_sonra, re.IGNORECASE)
        if not ogr_match:
            return None, f"Öğrenci no bulunamadı → {kalan_sonra[:30]}"
        ogr_no   = ogr_match.group(1).upper()
        blok_end += ogr_match.end()
        kalan2    = satir[blok_end:].strip()
        cep_match = re.match(r'^(05\d{9}|5\d{9})', kalan2)
        if cep_match:
            c = cep_match.group(1)
            cep = c if c.startswith('0') else '0' + c
            blok_end += cep_match.end()
    elif len(rakamlar) == 8:
        ogr_no = ('C' if cap else '') + rakamlar
    else:
        return None, f"Sayısal blok uzunluğu beklenmedik ({len(rakamlar)} hane) → {blok}"
    kalan    = satir[blok_end:].strip()
    kalan    = re.sub(r'\b\d{5,}\b', '', kalan)
    cevaplar = re.sub(r'[^A-Ea-e0 ]', '', kalan).replace(' ', '0').upper()
    if not cevaplar:
        return None, "Cevaplar boş"
    return {"ad_soyad": ad_soyad, "tc": tc, "ogr_no": ogr_no, "cevaplar": cevaplar, "cep": cep}, None


def ogrenci_puanla(cevaplar, anahtar):
    puan = 100 / len(anahtar)
    cevaplar = cevaplar.ljust(len(anahtar), '0')[:len(anahtar)]
    sonuc = []
    for c, a in zip(cevaplar, anahtar):
        if a.upper() == 'X':
            sonuc.append(round(puan, 4))
        elif c not in ('0', ' ', '') and c == a:
            sonuc.append(round(puan, 4))
        else:
            sonuc.append(0)
    return sonuc


def isle(metin, anahtar):
    satirlar = metin.splitlines()
    sonuclar, hatalar = [], []
    for i, satir in enumerate(satirlar, 1):
        veri, hata = satir_parse_et(satir)
        if hata:
            hatalar.append(f"Satır {i}: {hata}")
            continue
        if veri is None:
            continue
        puanlar = ogrenci_puanla(veri["cevaplar"], anahtar)
        kayit = {
            "ogr_no":   veri["ogr_no"],
            "ad_soyad": veri["ad_soyad"],
            "tc":       veri["tc"],
            "cep":      veri["cep"],
            "cevaplar": veri["cevaplar"],
        }
        for s, p in enumerate(puanlar, 1):
            kayit[f"S{s}"] = p
        kayit["toplam"] = round(sum(puanlar), 2)
        sonuclar.append(kayit)
    return sonuclar, hatalar


def soru_analizi_hesapla(sonuclar, anahtar):
    """Her soru için doğru yapma oranı ve istatistikler."""
    analiz = []
    n = len(sonuclar)
    puan = round(100 / len(anahtar), 4)
    for i, dogru_c in enumerate(anahtar, 1):
        dogru = sum(1 for r in sonuclar if r.get(f"S{i}", 0) > 0)
        yanlis = sum(1 for r in sonuclar if r.get(f"S{i}", 0) == 0
                     and len(r.get("cevaplar", "")) >= i
                     and r["cevaplar"][i-1] not in ('0', ' '))
        bos = n - dogru - yanlis
        pct = round(dogru / n * 100, 1) if n else 0
        analiz.append({
            "soru": i,
            "anahtar": dogru_c,
            "dogru": dogru,
            "yanlis": yanlis,
            "bos": bos,
            "pct": pct,
        })
    return analiz


def pdf_olustur(sonuclar, anahtar, dosya_adi="", ders_bilgisi=None, hoca_adi=""):
    """Analiz raporu PDF'i oluşturur."""

    # ── TTF Font Kaydı (Türkçe karakter desteği) ─────────────────────────────
    _registered = getattr(pdfmetrics, '_dv_registered', False)
    if not _registered:
        # Font dizini: önce sistem yolunu dene, sonra proje kökünü
        import os as _os
        _candidates = [
            "/usr/share/fonts/truetype/dejavu",
            "/usr/share/fonts/dejavu",
            _os.path.join(_os.path.dirname(__file__), "fonts"),
        ]
        _FONT_DIR = next((d for d in _candidates
                          if _os.path.exists(_os.path.join(d, "DejaVuSans.ttf"))), None)
        if _FONT_DIR is None:
            raise FileNotFoundError(
                "DejaVuSans.ttf bulunamadı. Lütfen 'fonts/' klasörüne DejaVu Sans .ttf dosyalarını ekleyin."
            )
        pdfmetrics.registerFont(TTFont("DV",     f"{_FONT_DIR}/DejaVuSans.ttf"))
        pdfmetrics.registerFont(TTFont("DV-B",   f"{_FONT_DIR}/DejaVuSans-Bold.ttf"))
        pdfmetrics.registerFont(TTFont("DV-I",   f"{_FONT_DIR}/DejaVuSans-Oblique.ttf"))
        pdfmetrics.registerFont(TTFont("DV-BI",  f"{_FONT_DIR}/DejaVuSans-BoldOblique.ttf"))
        pdfmetrics.registerFont(TTFont("DV-Mono",f"{_FONT_DIR}/DejaVuSansMono.ttf"))
        from reportlab.pdfbase.pdfmetrics import registerFontFamily
        registerFontFamily("DV", normal="DV", bold="DV-B", italic="DV-I", boldItalic="DV-BI")
        pdfmetrics._dv_registered = True

    # ── Renkler ────────────────────────────────────────────────────────────────
    C_PURPLE   = rl_colors.HexColor("#7c6af7")
    C_PURPLE_L = rl_colors.HexColor("#ede9fe")
    C_DARK     = rl_colors.HexColor("#1a1835")
    C_GREY     = rl_colors.HexColor("#6b6880")
    C_GREY_L   = rl_colors.HexColor("#f5f4ff")
    C_GREEN    = rl_colors.HexColor("#059669")
    C_GREEN_L  = rl_colors.HexColor("#d1fae5")
    C_RED      = rl_colors.HexColor("#dc2626")
    C_RED_L    = rl_colors.HexColor("#fee2e2")
    C_AMBER    = rl_colors.HexColor("#d97706")
    C_AMBER_L  = rl_colors.HexColor("#fef3c7")
    C_SKY      = rl_colors.HexColor("#0ea5e9")
    C_SKY_L    = rl_colors.HexColor("#e0f2fe")
    C_WHITE    = rl_colors.white
    C_BORDER   = rl_colors.HexColor("#dddaf0")
    C_ROW_ALT  = rl_colors.HexColor("#f8f7ff")

    # ── İstatistikler ──────────────────────────────────────────────────────────
    toplamlar  = [r["toplam"] for r in sonuclar]
    n          = len(toplamlar)
    ort        = np.mean(toplamlar)
    std        = np.std(toplamlar)
    medyan     = np.median(toplamlar)
    en_yuksek  = max(toplamlar)
    en_dusuk   = min(toplamlar)
    gecenler   = [t for t in toplamlar if t >= 50]
    gecme_say  = len(gecenler)
    gecme_pct  = round(gecme_say / n * 100, 1) if n else 0
    soru_sayisi = len(anahtar)
    analiz     = soru_analizi_hesapla(sonuclar, anahtar)

    buf = io.BytesIO()

    # ── Stil tanımları ─────────────────────────────────────────────────────────
    def ps(name, **kw):
        return ParagraphStyle(name, **kw)

    s_title   = ps("title",   fontName="DV-B",   fontSize=22, textColor=C_DARK,   spaceAfter=4,  leading=26)
    s_sub     = ps("sub",     fontName="DV",        fontSize=10, textColor=C_GREY,   spaceAfter=2)
    s_credit  = ps("credit",  fontName="DV-BI", fontSize=9, textColor=C_PURPLE, spaceAfter=0)
    s_h2      = ps("h2",      fontName="DV-B",   fontSize=13, textColor=C_DARK,   spaceBefore=18, spaceAfter=6)
    s_h3      = ps("h3",      fontName="DV-B",   fontSize=10, textColor=C_GREY,   spaceBefore=4,  spaceAfter=4)
    s_body    = ps("body",    fontName="DV",        fontSize=9,  textColor=C_DARK,   leading=14)
    s_small   = ps("small",   fontName="DV",        fontSize=8,  textColor=C_GREY)
    s_tc      = ps("tc",      fontName="DV",        fontSize=9,  textColor=C_DARK,   alignment=TA_CENTER)
    s_tc_bold = ps("tcb",     fontName="DV-B",   fontSize=9,  textColor=C_WHITE,  alignment=TA_CENTER)
    s_tr      = ps("tr",      fontName="DV",        fontSize=9,  textColor=C_DARK,   alignment=TA_RIGHT)

    # ── Header/Footer ──────────────────────────────────────────────────────────
    PAGE_W, PAGE_H = A4
    def on_page(canvas, doc):
        canvas.saveState()
        # Üst çizgi
        canvas.setStrokeColor(C_PURPLE)
        canvas.setLineWidth(3)
        canvas.line(2*cm, PAGE_H - 1.2*cm, PAGE_W - 2*cm, PAGE_H - 1.2*cm)
        # Alt footer
        canvas.setFont("DV", 7.5)
        canvas.setFillColor(C_GREY)
        hoca_footer = hoca_adi if hoca_adi else "Optik Notlandirma Sistemi"
        canvas.drawString(2*cm, 1.2*cm, f"Optik Notlandirma  |  {hoca_footer}")
        canvas.drawRightString(PAGE_W - 2*cm, 1.2*cm, f"Sayfa {doc.page}")
        canvas.restoreState()

    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=2*cm, rightMargin=2*cm,
        topMargin=2*cm, bottomMargin=2*cm,
        title="Optik Notlandirma Analiz Raporu",
        author=hoca_adi if hoca_adi else "Optik Notlandirma",
    )

    story = []

    # ══ 1. BAŞLIK SAYFASI ═════════════════════════════════════════════════════
    story.append(Spacer(1, 0.5*cm))
    story.append(Paragraph("Optik Notlandirma", s_title))
    story.append(Paragraph("Analiz Raporu", ps("t2", fontName="DV-B", fontSize=16,
                                                textColor=C_PURPLE, spaceAfter=6)))
    if dosya_adi:
        story.append(Paragraph(f"Kaynak: {dosya_adi}", s_sub))
    story.append(Paragraph(f"Cevap Anahtari: <b>{anahtar}</b>  ({soru_sayisi} soru)", s_sub))
    # Hoca ve ders bilgisi
    if hoca_adi:
        story.append(Paragraph(f"Hazirlayan: <b>{hoca_adi}</b>", s_credit))
    if ders_bilgisi:
        db = ders_bilgisi
        story.append(Spacer(1, 0.3*cm))
        ders_rows = []
        if db.get("ders_adi"):    ders_rows.append([Paragraph("<b>Ders Adi</b>", s_body),    Paragraph(db["ders_adi"], s_body)])
        if db.get("ders_kodu"):   ders_rows.append([Paragraph("<b>Ders Kodu</b>", s_body),   Paragraph(db["ders_kodu"], s_body)])
        if db.get("bolum"):       ders_rows.append([Paragraph("<b>Bolum</b>", s_body),       Paragraph(db["bolum"], s_body)])
        if db.get("donem"):       ders_rows.append([Paragraph("<b>Donem</b>", s_body),       Paragraph(db["donem"], s_body)])
        if db.get("akademik_yil"):ders_rows.append([Paragraph("<b>Akademik Yil</b>", s_body),Paragraph(db["akademik_yil"], s_body)])
        if ders_rows:
            d_tw = PAGE_W - 4*cm
            d_tbl = Table(ders_rows, colWidths=[d_tw*0.3, d_tw*0.7])
            d_tbl.setStyle(TableStyle([
                ("BACKGROUND", (0,0), (0,-1), C_GREY_L),
                ("FONTNAME",   (0,0), (0,-1), "DV-B"),
                ("GRID",       (0,0), (-1,-1), 0.4, C_BORDER),
                ("TOPPADDING", (0,0), (-1,-1), 5),
                ("BOTTOMPADDING",(0,0),(-1,-1), 5),
                ("LEFTPADDING",(0,0),(-1,-1), 8),
            ]))
            story.append(d_tbl)
    story.append(HRFlowable(width="100%", thickness=1.5, color=C_PURPLE,
                             spaceAfter=16, spaceBefore=10))

    # ══ 2. SINIF İSTATİSTİKLERİ ═══════════════════════════════════════════════
    story.append(Paragraph("Sinif Istatistikleri", s_h2))

    istat_data = [
        ["", "Deger", "", ""],
        ["Toplam Ogrenci",   str(n),               "Gecen (>=50)",    str(gecme_say)],
        ["Sinif Ortalamasi", f"{ort:.2f}",          "Gecme Orani",     f"%{gecme_pct}"],
        ["Standart Sapma",   f"{std:.2f}",          "Kalan",           str(n - gecme_say)],
        ["Medyan Puan",      f"{medyan:.2f}",       "En Yuksek",       f"{en_yuksek:.2f}"],
        ["Soru Sayisi",      str(soru_sayisi),      "En Dusuk",        f"{en_dusuk:.2f}"],
    ]

    # 2 sütunlu kart grid yerine düzenli tablo
    stat_rows = [
        [Paragraph("<b>Istatistik</b>", s_tc_bold), Paragraph("<b>Deger</b>", s_tc_bold),
         Paragraph("<b>Istatistik</b>", s_tc_bold), Paragraph("<b>Deger</b>", s_tc_bold)],
        [Paragraph("Toplam Ogrenci",   s_body), Paragraph(f"<b>{n}</b>",              ps("vb", fontName="DV-B", fontSize=11, textColor=C_PURPLE, alignment=TA_CENTER)),
         Paragraph("Gecen (>=50)",     s_body), Paragraph(f"<b>{gecme_say}</b>",      ps("vb2",fontName="DV-B", fontSize=11, textColor=C_GREEN, alignment=TA_CENTER))],
        [Paragraph("Sinif Ortalamasi", s_body), Paragraph(f"<b>{ort:.2f}</b>",        ps("vb3", fontName="DV-B", fontSize=11, textColor=C_PURPLE, alignment=TA_CENTER)),
         Paragraph("Gecme Orani",      s_body), Paragraph(f"<b>%{gecme_pct}</b>",     ps("vb4", fontName="DV-B", fontSize=11, textColor=C_GREEN, alignment=TA_CENTER))],
        [Paragraph("Standart Sapma",   s_body), Paragraph(f"<b>{std:.2f}</b>",        ps("vb5", fontName="DV-B", fontSize=11, textColor=C_SKY, alignment=TA_CENTER)),
         Paragraph("Kalan",            s_body), Paragraph(f"<b>{n - gecme_say}</b>",  ps("vb6", fontName="DV-B", fontSize=11, textColor=C_RED, alignment=TA_CENTER))],
        [Paragraph("Medyan",           s_body), Paragraph(f"<b>{medyan:.2f}</b>",     ps("vb7", fontName="DV-B", fontSize=11, textColor=C_DARK, alignment=TA_CENTER)),
         Paragraph("En Yuksek",        s_body), Paragraph(f"<b>{en_yuksek:.2f}</b>",  ps("vb8", fontName="DV-B", fontSize=11, textColor=C_GREEN, alignment=TA_CENTER))],
        [Paragraph("Soru Sayisi",      s_body), Paragraph(f"<b>{soru_sayisi}</b>",    ps("vb9", fontName="DV-B", fontSize=11, textColor=C_DARK, alignment=TA_CENTER)),
         Paragraph("En Dusuk",         s_body), Paragraph(f"<b>{en_dusuk:.2f}</b>",   ps("vb10",fontName="DV-B", fontSize=11, textColor=C_RED, alignment=TA_CENTER))],
    ]

    col_w = (PAGE_W - 4*cm) / 4
    stat_tbl = Table(stat_rows, colWidths=[col_w*1.4, col_w*0.6, col_w*1.4, col_w*0.6])
    stat_tbl.setStyle(TableStyle([
        ("BACKGROUND",  (0,0), (-1,0),  C_DARK),
        ("TEXTCOLOR",   (0,0), (-1,0),  C_WHITE),
        ("FONTNAME",    (0,0), (-1,0),  "DV-B"),
        ("FONTSIZE",    (0,0), (-1,0),  9),
        ("ALIGN",       (0,0), (-1,-1), "CENTER"),
        ("VALIGN",      (0,0), (-1,-1), "MIDDLE"),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [C_WHITE, C_ROW_ALT]),
        ("GRID",        (0,0), (-1,-1), 0.5, C_BORDER),
        ("ROUNDEDCORNERS", [4]),
        ("TOPPADDING",  (0,0), (-1,-1), 7),
        ("BOTTOMPADDING",(0,0),(-1,-1), 7),
        ("LEFTPADDING", (0,0), (-1,-1), 10),
        ("RIGHTPADDING",(0,0), (-1,-1), 10),
    ]))
    story.append(stat_tbl)

    # ══ 3. GEÇTİ / KALDI ÖZETİ ════════════════════════════════════════════════
    story.append(Spacer(1, 0.4*cm))
    story.append(Paragraph("Gecti / Kaldi Ozeti", s_h2))

    gc_data = [
        [Paragraph("<b>Durum</b>",   s_tc_bold),
         Paragraph("<b>Sayi</b>",    s_tc_bold),
         Paragraph("<b>Oran</b>",    s_tc_bold),
         Paragraph("<b>Puan Esigi</b>", s_tc_bold)],
        [Paragraph("Gecti", ps("gc", fontName="DV-B", fontSize=10, textColor=C_GREEN, alignment=TA_CENTER)),
         Paragraph(str(gecme_say), ps("gcv", fontName="DV-B", fontSize=14, textColor=C_GREEN, alignment=TA_CENTER)),
         Paragraph(f"%{gecme_pct}", ps("gcr", fontName="DV-B", fontSize=12, textColor=C_GREEN, alignment=TA_CENTER)),
         Paragraph(">= 50", s_tc)],
        [Paragraph("Kaldi", ps("kl", fontName="DV-B", fontSize=10, textColor=C_RED, alignment=TA_CENTER)),
         Paragraph(str(n - gecme_say), ps("klv", fontName="DV-B", fontSize=14, textColor=C_RED, alignment=TA_CENTER)),
         Paragraph(f"%{round(100 - gecme_pct, 1)}", ps("klr", fontName="DV-B", fontSize=12, textColor=C_RED, alignment=TA_CENTER)),
         Paragraph("< 50", s_tc)],
    ]
    tw = PAGE_W - 4*cm
    gc_tbl = Table(gc_data, colWidths=[tw*0.3, tw*0.2, tw*0.25, tw*0.25])
    gc_tbl.setStyle(TableStyle([
        ("BACKGROUND",   (0,0), (-1,0), C_DARK),
        ("BACKGROUND",   (0,1), (-1,1), C_GREEN_L),
        ("BACKGROUND",   (0,2), (-1,2), C_RED_L),
        ("GRID",         (0,0), (-1,-1), 0.5, C_BORDER),
        ("ALIGN",        (0,0), (-1,-1), "CENTER"),
        ("VALIGN",       (0,0), (-1,-1), "MIDDLE"),
        ("TOPPADDING",   (0,0), (-1,-1), 8),
        ("BOTTOMPADDING",(0,0), (-1,-1), 8),
    ]))
    story.append(gc_tbl)

    # ══ 4. PUAN DAĞILIMI ═══════════════════════════════════════════════════════
    story.append(Paragraph("Puan Dagilimi", s_h2))

    araliklar = [
        ("0-24",   0,  24,  "#f87171"),
        ("25-49", 25,  49,  "#fb923c"),
        ("50-64", 50,  64,  "#fbbf24"),
        ("65-79", 65,  79,  "#34d399"),
        ("80-89", 80,  89,  "#22d3ee"),
        ("90-100",90, 100,  "#7c6af7"),
    ]
    cnts = [sum(1 for t in toplamlar if lo <= t <= hi) for _, lo, hi, _ in araliklar]
    max_cnt = max(cnts) if cnts else 1

    # Grafik çiz (reportlab Drawing)
    bar_w   = PAGE_W - 4*cm
    bar_h   = 5.5*cm
    lbl_w   = 1.5*cm
    bar_area= bar_w - lbl_w - 1.2*cm
    row_h   = bar_h / len(araliklar)

    drw = Drawing(bar_w, bar_h)
    for idx, ((lbl, lo, hi, hex_c), cnt) in enumerate(zip(araliklar, cnts)):
        y = bar_h - (idx + 1) * row_h + row_h * 0.15
        fill_w = (cnt / max_cnt) * bar_area if max_cnt else 0

        # Arka plan çubuğu (gri)
        bg = Rect(lbl_w, y, bar_area, row_h * 0.7,
                  fillColor=rl_colors.HexColor("#f0effe"), strokeColor=None)
        drw.add(bg)

        if fill_w > 0:
            bar = Rect(lbl_w, y, fill_w, row_h * 0.7,
                       fillColor=rl_colors.HexColor(hex_c), strokeColor=None)
            drw.add(bar)

            pct_str = f"%{round(cnt/n*100,1)}  ({cnt})" if n else ""
            lbl_x   = lbl_w + fill_w + 4
            drw.add(String(lbl_x, y + row_h * 0.22,
                           pct_str,
                           fontName="DV", fontSize=7.5,
                           fillColor=rl_colors.HexColor("#4a4770")))

        drw.add(String(0, y + row_h * 0.22, lbl,
                       fontName="DV", fontSize=8,
                       fillColor=rl_colors.HexColor("#6b6880")))

    story.append(drw)

    # ══ 5. SORU ANALİZİ ════════════════════════════════════════════════════════
    story.append(PageBreak())
    story.append(Paragraph("Soru Analizi", s_h2))
    story.append(Paragraph(
        "Dogru Yapma Orani:  Kolay >= %70  |  Orta %40-69  |  Zor < %40",
        ps("leg", fontName="DV", fontSize=8, textColor=C_GREY, spaceAfter=8)
    ))

    # Soru kartlarını tablo olarak düzenle (8 sütun)
    COLS = 8
    qa_header = [Paragraph("<b>Soru</b>", s_tc_bold),
                 Paragraph("<b>Cevap</b>", s_tc_bold),
                 Paragraph("<b>Dogru</b>", s_tc_bold),
                 Paragraph("<b>Yanlis</b>", s_tc_bold),
                 Paragraph("<b>Bos</b>", s_tc_bold),
                 Paragraph("<b>%Dogru</b>", s_tc_bold),
                 Paragraph("<b>Zorluk</b>", s_tc_bold),
                 Paragraph("<b>Durum</b>", s_tc_bold)]

    qa_rows = [qa_header]
    for a in analiz:
        if a["pct"] >= 70:
            zorluk_txt, z_fg, z_bg = "Kolay", C_GREEN, C_GREEN_L
        elif a["pct"] >= 40:
            zorluk_txt, z_fg, z_bg = "Orta",  C_AMBER, C_AMBER_L
        else:
            zorluk_txt, z_fg, z_bg = "Zor",   C_RED,   C_RED_L

        bar_cells = int(a["pct"] / 10)
        bar_str   = "█" * bar_cells + "░" * (10 - bar_cells)

        qa_rows.append([
            Paragraph(f"S{a['soru']}", s_tc),
            Paragraph(f"<b>{a['anahtar']}</b>", ps("ans", fontName="DV-B", fontSize=9, textColor=C_PURPLE, alignment=TA_CENTER)),
            Paragraph(str(a["dogru"]),  ps("d", fontName="DV-B", fontSize=9, textColor=C_GREEN, alignment=TA_CENTER)),
            Paragraph(str(a["yanlis"]), ps("y", fontName="DV-B", fontSize=9, textColor=C_RED,   alignment=TA_CENTER)),
            Paragraph(str(a["bos"]),    ps("b", fontName="DV",      fontSize=9, textColor=C_GREY,  alignment=TA_CENTER)),
            Paragraph(f"{a['pct']:.1f}%", ps("p", fontName="DV-B", fontSize=9, textColor=z_fg, alignment=TA_CENTER)),
            Paragraph(zorluk_txt, ps(f"z{a['soru']}", fontName="DV-B", fontSize=8.5, textColor=z_fg, alignment=TA_CENTER)),
            Paragraph(bar_str,    ps("bar", fontName="DV-Mono", fontSize=7, textColor=z_fg, alignment=TA_CENTER)),
        ])

    tw = PAGE_W - 4*cm
    qa_tbl = Table(qa_rows, colWidths=[tw*0.08, tw*0.10, tw*0.09, tw*0.09,
                                        tw*0.07, tw*0.10, tw*0.10, tw*0.37])
    qa_style = [
        ("BACKGROUND",   (0,0), (-1,0),  C_DARK),
        ("GRID",         (0,0), (-1,-1), 0.4, C_BORDER),
        ("ALIGN",        (0,0), (-1,-1), "CENTER"),
        ("VALIGN",       (0,0), (-1,-1), "MIDDLE"),
        ("TOPPADDING",   (0,0), (-1,-1), 5),
        ("BOTTOMPADDING",(0,0), (-1,-1), 5),
        ("FONTSIZE",     (0,0), (-1,0),  8.5),
        ("NOSPLIT",      (0,0), (-1,0)),
    ]
    # Zorluk sütununa arka plan rengini satır satır uygula
    for row_idx, a in enumerate(analiz, start=1):
        if a["pct"] >= 70:
            bg = C_GREEN_L
        elif a["pct"] >= 40:
            bg = C_AMBER_L
        else:
            bg = C_RED_L
        qa_style.append(("BACKGROUND", (6, row_idx), (7, row_idx), bg))
        if row_idx % 2 == 0:
            for col in [0,1,2,3,4,5]:
                qa_style.append(("BACKGROUND", (col, row_idx), (col, row_idx), C_ROW_ALT))
    qa_tbl.setStyle(TableStyle(qa_style))
    story.append(qa_tbl)

    # ══ 6. ÖNİZLEME TABLOSU — TÜM ÖĞRENCİLER ═════════════════════════════════
    story.append(PageBreak())
    story.append(Paragraph("Ogrenci Listesi", s_h2))

    def ogr_sort_key(r):
        ogr = r["ogr_no"]
        num = re.sub(r'[^0-9]', '', ogr)
        return (ogr.startswith('C'), int(num) if num else 0)

    sirali = sorted(sonuclar, key=ogr_sort_key)

    stu_header = [
        Paragraph("<b>#</b>",            s_tc_bold),
        Paragraph("<b>Ogrenci No</b>",   s_tc_bold),
        Paragraph("<b>Ad Soyad</b>",     s_tc_bold),
        Paragraph("<b>Toplam</b>",       s_tc_bold),
        Paragraph("<b>Durum</b>",        s_tc_bold),
    ]
    stu_rows = [stu_header]
    for idx, r in enumerate(sirali, 1):
        gecti    = r["toplam"] >= 50
        durum_fg = C_GREEN if gecti else C_RED
        durum_bg = C_GREEN_L if gecti else C_RED_L
        durum_tx = "Gecti" if gecti else "Kaldi"
        row_bg   = C_WHITE if idx % 2 else C_ROW_ALT
        stu_rows.append([
            Paragraph(str(idx), ps(f"rn{idx}", fontName="DV", fontSize=8, textColor=C_PURPLE, alignment=TA_CENTER)),
            Paragraph(r["ogr_no"],   ps(f"on{idx}", fontName="DV-B", fontSize=8.5, textColor=C_DARK, alignment=TA_CENTER)),
            Paragraph(r["ad_soyad"], ps(f"ad{idx}", fontName="DV",      fontSize=8.5, textColor=C_DARK)),
            Paragraph(f"<b>{r['toplam']:.2f}</b>", ps(f"tp{idx}", fontName="DV-B", fontSize=9,
                       textColor=durum_fg, alignment=TA_CENTER)),
            Paragraph(durum_tx, ps(f"dt{idx}", fontName="DV-B", fontSize=8,
                      textColor=durum_fg, alignment=TA_CENTER)),
        ])

    tw = PAGE_W - 4*cm
    stu_tbl = Table(stu_rows, colWidths=[tw*0.07, tw*0.18, tw*0.42, tw*0.17, tw*0.16],
                    repeatRows=1)
    stu_style = [
        ("BACKGROUND",   (0,0), (-1,0), C_DARK),
        ("GRID",         (0,0), (-1,-1), 0.4, C_BORDER),
        ("ALIGN",        (0,0), (-1,-1), "CENTER"),
        ("ALIGN",        (2,1), (2,-1),  "LEFT"),
        ("VALIGN",       (0,0), (-1,-1), "MIDDLE"),
        ("TOPPADDING",   (0,0), (-1,-1), 5),
        ("BOTTOMPADDING",(0,0), (-1,-1), 5),
        ("LEFTPADDING",  (2,1), (2,-1),  6),
    ]
    for idx, r in enumerate(sirali, 1):
        gecti  = r["toplam"] >= 50
        row_bg = C_WHITE if idx % 2 else C_ROW_ALT
        for col in [0,1,2,3]:
            stu_style.append(("BACKGROUND", (col, idx), (col, idx), row_bg))
        stu_style.append(("BACKGROUND", (4, idx), (4, idx), C_GREEN_L if gecti else C_RED_L))
    stu_tbl.setStyle(TableStyle(stu_style))
    story.append(stu_tbl)

    # ── Build ──────────────────────────────────────────────────────────────────
    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    buf.seek(0)
    return buf


def excel_olustur(sonuclar, anahtar):
    """Şık, renkli, sıralı Excel oluştur."""
    soru_sayisi    = len(anahtar)
    puan_per_s     = round(100 / soru_sayisi, 4)
    soru_kolonlari = [f"S{i}" for i in range(1, soru_sayisi + 1)]
    soru_baslik    = [f"Soru {i}" for i in range(1, soru_sayisi + 1)]

    # Öğrenci numarasına göre sırala
    def ogr_sort_key(r):
        ogr = r["ogr_no"]
        cap = ogr.startswith('C')
        num = re.sub(r'[^0-9]', '', ogr)
        return (cap, int(num) if num else 0)

    sonuclar_sirali = sorted(sonuclar, key=ogr_sort_key)

    # ── DataFrames ────────────────────────────────────────────────────────────
    # Sheet 1: Proliz Not Girişi
    rows_proliz = []
    for idx, r in enumerate(sonuclar_sirali, 1):
        row = {"#": idx, "Öğrenci Numarası": r["ogr_no"]}
        for i in range(1, soru_sayisi + 1):
            row[f"Soru {i}"] = r[f"S{i}"]
        rows_proliz.append(row)
    df_proliz = pd.DataFrame(rows_proliz)

    # Sheet 2: Detaylı Liste
    rows_detay = []
    for idx, r in enumerate(sonuclar_sirali, 1):
        row = {
            "#":                idx,
            "Öğrenci Numarası": r["ogr_no"],
            "Adı Soyadı":       r["ad_soyad"],
            "TC No":            r.get("tc", ""),
            "Cep Telefonu":     r.get("cep", ""),
            "Toplam Puan":      r["toplam"],
            "Başarı Durumu":    "✓ Geçti" if r["toplam"] >= 50 else "✗ Kaldı",
        }
        for i in range(1, soru_sayisi + 1):
            row[f"S{i}"] = r[f"S{i}"]
        rows_detay.append(row)
    df_detay = pd.DataFrame(rows_detay)

    # Sheet 3: Özet
    rows_ozet = []
    for idx, r in enumerate(sonuclar_sirali, 1):
        rows_ozet.append({
            "#":                idx,
            "Öğrenci Numarası": r["ogr_no"],
            "Adı Soyadı":       r["ad_soyad"],
            "TC No":            r.get("tc", ""),
            "Cep Telefonu":     r.get("cep", ""),
            "Toplam Puan":      r["toplam"],
            "Başarı Durumu":    "Geçti" if r["toplam"] >= 50 else "Kaldı",
        })
    df_ozet = pd.DataFrame(rows_ozet)

    # Sheet 4: Soru Analizi
    analiz = soru_analizi_hesapla(sonuclar, anahtar)
    rows_analiz = []
    for a in analiz:
        zorluk = "Kolay" if a["pct"] >= 70 else ("Orta" if a["pct"] >= 40 else "Zor")
        rows_analiz.append({
            "Soru No":          a["soru"],
            "Doğru Cevap":      a["anahtar"],
            "Doğru Yapan":      a["dogru"],
            "Yanlış Yapan":     a["yanlis"],
            "Boş Bırakan":      a["bos"],
            "Doğru Oranı (%)":  a["pct"],
            "Zorluk":           zorluk,
        })
    df_analiz = pd.DataFrame(rows_analiz)

    # Sheet 5: İstatistik
    toplamlar = [r["toplam"] for r in sonuclar]
    gecenler  = [t for t in toplamlar if t >= 50]
    rows_istat = [
        {"İstatistik": "Toplam Öğrenci",      "Değer": len(sonuclar)},
        {"İstatistik": "Geçen Öğrenci",        "Değer": len(gecenler)},
        {"İstatistik": "Kalan Öğrenci",        "Değer": len(sonuclar) - len(gecenler)},
        {"İstatistik": "Geçme Oranı (%)",      "Değer": round(len(gecenler)/len(sonuclar)*100,1) if sonuclar else 0},
        {"İstatistik": "Sınıf Ortalaması",     "Değer": round(np.mean(toplamlar), 2) if toplamlar else 0},
        {"İstatistik": "Standart Sapma",        "Değer": round(np.std(toplamlar), 2) if toplamlar else 0},
        {"İstatistik": "En Yüksek Puan",       "Değer": max(toplamlar) if toplamlar else 0},
        {"İstatistik": "En Düşük Puan",        "Değer": min(toplamlar) if toplamlar else 0},
        {"İstatistik": "Medyan Puan",           "Değer": round(np.median(toplamlar), 2) if toplamlar else 0},
        {"İstatistik": "Soru Sayısı",           "Değer": soru_sayisi},
        {"İstatistik": "Soru Başına Puan",      "Değer": puan_per_s},
        {"İstatistik": "Cevap Anahtarı",        "Değer": anahtar},
    ]
    df_istat = pd.DataFrame(rows_istat)

    # Sheet 6: Ham TXT
    rows_ham = []
    for idx, r in enumerate(sonuclar_sirali, 1):
        rows_ham.append({
            "#":                idx,
            "Öğrenci Numarası": r["ogr_no"],
            "Adı Soyadı":       r["ad_soyad"],
            "TC No":            r.get("tc", ""),
            "Cep Telefonu":     r.get("cep", ""),
            "Ham Cevaplar":     r.get("cevaplar", ""),
        })
    df_ham = pd.DataFrame(rows_ham)

    # ── Excel Yaz ────────────────────────────────────────────────────────────
    buf = io.BytesIO()
    with pd.ExcelWriter(buf, engine="openpyxl") as writer:
        df_proliz.to_excel(writer,  sheet_name="Proliz Not Girişi", index=False)
        df_detay.to_excel(writer,   sheet_name="Detaylı Liste",      index=False)
        df_ozet.to_excel(writer,    sheet_name="Özet",               index=False)
        df_analiz.to_excel(writer,  sheet_name="Soru Analizi",       index=False)
        df_istat.to_excel(writer,   sheet_name="İstatistik",          index=False)
        df_ham.to_excel(writer,     sheet_name="Ham TXT",             index=False)

    buf.seek(0)
    wb = load_workbook(buf)
    _excel_stillendir(wb, sonuclar_sirali, anahtar, df_analiz)

    buf2 = io.BytesIO()
    wb.save(buf2)
    buf2.seek(0)
    return buf2


def _stil(bold=False, color="000000", bg=None, size=10, align="left",
          valign="center", wrap=False, border=False, italic=False):
    f = Font(bold=bold, color=color, size=size, italic=italic,
             name="Calibri")
    a = Alignment(horizontal=align, vertical=valign, wrap_text=wrap)
    fill = PatternFill("solid", fgColor=bg) if bg else PatternFill()
    sides = Side(style="thin", color="D0CEDF") if border else Side()
    b = Border(left=sides, right=sides, top=sides, bottom=sides)
    return f, a, fill, b


def _excel_stillendir(wb, sonuclar_sirali, anahtar, df_analiz):
    soru_sayisi = len(anahtar)

    # Renk paleti
    C_HEADER_BG  = "1E1B35"   # koyu mor başlık
    C_HEADER_FG  = "FFFFFF"
    C_ALT1       = "F8F7FF"   # açık satır
    C_ALT2       = "FFFFFF"   # beyaz satır
    C_ACCENT     = "7C6AF7"   # mor vurgu
    C_GREEN_BG   = "EAFAF1"
    C_RED_BG     = "FEF2F2"
    C_GREEN_FG   = "1A6B3C"
    C_RED_FG     = "9B1C1C"
    C_EASY       = "D1FAE5"
    C_MID        = "FEF3C7"
    C_HARD       = "FEE2E2"
    C_NUM_BG     = "EEF2FF"   # sıra no arkaplan

    def header_row(ws, cols):
        for col_idx, col_name in enumerate(cols, 1):
            c = ws.cell(row=1, column=col_idx, value=col_name)
            c.font      = Font(bold=True, color=C_HEADER_FG, size=10, name="Calibri")
            c.fill      = PatternFill("solid", fgColor=C_HEADER_BG)
            c.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
            c.border    = Border(
                left=Side(style="thin", color="4A4770"),
                right=Side(style="thin", color="4A4770"),
                bottom=Side(style="medium", color=C_ACCENT),
            )
        ws.row_dimensions[1].height = 28

    def alt_fill(row_idx):
        return PatternFill("solid", fgColor=C_ALT1 if row_idx % 2 == 0 else C_ALT2)

    def auto_width(ws, min_w=8, max_w=30):
        for col in ws.columns:
            length = max(
                (len(str(c.value)) if c.value is not None else 0)
                for c in col
            )
            ws.column_dimensions[get_column_letter(col[0].column)].width = max(min_w, min(length + 2, max_w))

    thin_border = Border(
        left=Side(style="thin", color="E0DEEE"),
        right=Side(style="thin", color="E0DEEE"),
        top=Side(style="thin", color="E0DEEE"),
        bottom=Side(style="thin", color="E0DEEE"),
    )

    # ── Sheet 1: Proliz Not Girişi ──────────────────────────────────────────
    ws = wb["Proliz Not Girişi"]
    cols = list(ws.iter_cols(1, ws.max_column, 1, 1))
    col_names = [c[0].value for c in cols]
    header_row(ws, col_names)
    for row in ws.iter_rows(min_row=2, max_row=ws.max_row):
        for ci, cell in enumerate(row):
            cell.fill   = alt_fill(row[0].row)
            cell.border = thin_border
            cell.font   = Font(name="Calibri", size=10,
                               color="5B5880" if ci == 0 else "1A1835")
            cell.alignment = Alignment(horizontal="center" if ci != 1 else "left",
                                       vertical="center")
            if ci == 0:  # # sütunu
                cell.fill = PatternFill("solid", fgColor=C_NUM_BG)
                cell.font = Font(name="Calibri", size=9, color="7C6AF7", bold=True)
            elif ci == 1:  # Öğrenci No
                cell.font = Font(name="Calibri", size=10, bold=True, color="1A1835")
            elif ci >= 2:  # puan hücreleri
                if cell.value and float(cell.value) > 0:
                    cell.font = Font(name="Calibri", size=10, color="1A6B3C", bold=True)
                else:
                    cell.font = Font(name="Calibri", size=10, color="9B1C1C")
    ws.freeze_panes = "C2"
    auto_width(ws)
    ws.column_dimensions["A"].width = 5

    # ── Sheet 2: Detaylı Liste ──────────────────────────────────────────────
    ws = wb["Detaylı Liste"]
    cols = list(ws.iter_cols(1, ws.max_column, 1, 1))
    col_names = [c[0].value for c in cols]
    header_row(ws, col_names)

    # Toplam puan ve başarı durumu kolon indexlerini bul
    try:
        toplam_col = col_names.index("Toplam Puan") + 1
        basari_col = col_names.index("Başarı Durumu") + 1
    except ValueError:
        toplam_col = basari_col = None

    for row in ws.iter_rows(min_row=2, max_row=ws.max_row):
        gecti = None
        if toplam_col:
            puan_val = row[toplam_col - 1].value
            gecti = puan_val is not None and float(puan_val) >= 50

        for ci, cell in enumerate(row):
            cell.border = thin_border
            cell.alignment = Alignment(horizontal="center", vertical="center")

            if ci == 0:  # Sıra no
                cell.fill = PatternFill("solid", fgColor=C_NUM_BG)
                cell.font = Font(name="Calibri", size=9, color="7C6AF7", bold=True)
            elif toplam_col and ci == toplam_col - 1:
                cell.fill = PatternFill("solid", fgColor=C_GREEN_BG if gecti else C_RED_BG)
                cell.font = Font(name="Calibri", size=10, bold=True,
                                 color=C_GREEN_FG if gecti else C_RED_FG)
            elif basari_col and ci == basari_col - 1:
                cell.fill = PatternFill("solid", fgColor=C_GREEN_BG if gecti else C_RED_BG)
                cell.font = Font(name="Calibri", size=10, bold=True,
                                 color=C_GREEN_FG if gecti else C_RED_FG)
            else:
                cell.fill = alt_fill(row[0].row)
                cell.font = Font(name="Calibri", size=10, color="1A1835")
    ws.freeze_panes = "C2"
    auto_width(ws)
    ws.column_dimensions["A"].width = 5

    # ── Sheet 3: Özet ───────────────────────────────────────────────────────
    ws = wb["Özet"]
    cols = list(ws.iter_cols(1, ws.max_column, 1, 1))
    col_names = [c[0].value for c in cols]
    header_row(ws, col_names)
    try:
        toplam_col_o = col_names.index("Toplam Puan") + 1
        basari_col_o = col_names.index("Başarı Durumu") + 1
    except ValueError:
        toplam_col_o = basari_col_o = None

    for row in ws.iter_rows(min_row=2, max_row=ws.max_row):
        gecti = None
        if toplam_col_o:
            pv = row[toplam_col_o - 1].value
            gecti = pv is not None and float(pv) >= 50
        for ci, cell in enumerate(row):
            cell.border = thin_border
            cell.alignment = Alignment(horizontal="center", vertical="center")
            if ci == 0:
                cell.fill = PatternFill("solid", fgColor=C_NUM_BG)
                cell.font = Font(name="Calibri", size=9, color="7C6AF7", bold=True)
            elif toplam_col_o and ci == toplam_col_o - 1:
                cell.fill = PatternFill("solid", fgColor=C_GREEN_BG if gecti else C_RED_BG)
                cell.font = Font(name="Calibri", size=10, bold=True,
                                 color=C_GREEN_FG if gecti else C_RED_FG)
            elif basari_col_o and ci == basari_col_o - 1:
                cell.fill = PatternFill("solid", fgColor=C_GREEN_BG if gecti else C_RED_BG)
                cell.font = Font(name="Calibri", size=10, bold=True,
                                 color=C_GREEN_FG if gecti else C_RED_FG)
            else:
                cell.fill = alt_fill(row[0].row)
                cell.font = Font(name="Calibri", size=10, color="1A1835")
    auto_width(ws)
    ws.column_dimensions["A"].width = 5

    # ── Sheet 4: Soru Analizi ───────────────────────────────────────────────
    ws = wb["Soru Analizi"]
    cols = list(ws.iter_cols(1, ws.max_column, 1, 1))
    col_names = [c[0].value for c in cols]
    header_row(ws, col_names)
    try:
        zorluk_col = col_names.index("Zorluk") + 1
        oran_col   = col_names.index("Doğru Oranı (%)") + 1
    except ValueError:
        zorluk_col = oran_col = None

    for row in ws.iter_rows(min_row=2, max_row=ws.max_row):
        zorluk_val = row[zorluk_col - 1].value if zorluk_col else None
        bg = C_EASY if zorluk_val == "Kolay" else (C_MID if zorluk_val == "Orta" else C_HARD)
        fg = C_GREEN_FG if zorluk_val == "Kolay" else ("92400E" if zorluk_val == "Orta" else C_RED_FG)
        for ci, cell in enumerate(row):
            cell.border = thin_border
            cell.alignment = Alignment(horizontal="center", vertical="center")
            cell.fill = alt_fill(row[0].row)
            cell.font = Font(name="Calibri", size=10, color="1A1835")
            if zorluk_col and ci == zorluk_col - 1:
                cell.fill = PatternFill("solid", fgColor=bg)
                cell.font = Font(name="Calibri", size=10, bold=True, color=fg)
            if oran_col and ci == oran_col - 1:
                v = cell.value
                if v is not None:
                    ov = float(v)
                    if ov >= 70:
                        cell.font = Font(name="Calibri", size=10, bold=True, color=C_GREEN_FG)
                    elif ov >= 40:
                        cell.font = Font(name="Calibri", size=10, bold=True, color="92400E")
                    else:
                        cell.font = Font(name="Calibri", size=10, bold=True, color=C_RED_FG)
    auto_width(ws)

    # Koşullu biçimlendirme: Doğru Oranı sütununa renk skalası
    if oran_col:
        col_letter = get_column_letter(oran_col)
        ws.conditional_formatting.add(
            f"{col_letter}2:{col_letter}{ws.max_row}",
            ColorScaleRule(
                start_type="num", start_value=0,   start_color="FEE2E2",
                mid_type="num",   mid_value=50,    mid_color="FEF3C7",
                end_type="num",   end_value=100,   end_color="D1FAE5",
            )
        )

    # ── Sheet 5: İstatistik ─────────────────────────────────────────────────
    ws = wb["İstatistik"]
    header_row(ws, ["İstatistik", "Değer"])
    for row in ws.iter_rows(min_row=2, max_row=ws.max_row):
        for ci, cell in enumerate(row):
            cell.border = thin_border
            cell.alignment = Alignment(horizontal="left" if ci == 0 else "right",
                                       vertical="center")
            if ci == 0:
                cell.fill = PatternFill("solid", fgColor=C_ALT1)
                cell.font = Font(name="Calibri", size=10, bold=True, color="3B3860")
            else:
                cell.fill = PatternFill("solid", fgColor=C_ALT2)
                cell.font = Font(name="Calibri", size=10, color="1A1835")
    auto_width(ws)

    # ── Sheet 6: Ham TXT ────────────────────────────────────────────────────
    ws = wb["Ham TXT"]
    cols = list(ws.iter_cols(1, ws.max_column, 1, 1))
    col_names = [c[0].value for c in cols]
    header_row(ws, col_names)
    for row in ws.iter_rows(min_row=2, max_row=ws.max_row):
        for ci, cell in enumerate(row):
            cell.border = thin_border
            cell.alignment = Alignment(horizontal="center" if ci != 4 else "left",
                                       vertical="center")
            cell.fill = alt_fill(row[0].row)
            cell.font = Font(name="Calibri", size=10,
                             color="7C6AF7" if ci == 0 else "1A1835",
                             bold=(ci == 0))
            if ci == 5:  # Ham Cevaplar
                cell.font = Font(name="DV-Mono", size=9, color="4A4770")
    auto_width(ws, max_w=50)
    ws.column_dimensions["A"].width = 5


# ══════════════════════════════════════════════════════════════════════════════
# ARAYÜZ
# ══════════════════════════════════════════════════════════════════════════════

# ── Login Sistemi ────────────────────────────────────────────────────────────
KULLANICI_ADI = "tekis-jet"
SIFRE_HASH    = hashlib.sha256("tekis2024".encode()).hexdigest()

def sifre_dogrula(sifre):
    return hashlib.sha256(sifre.encode()).hexdigest() == SIFRE_HASH

if "giris_yapildi" not in st.session_state:
    st.session_state.giris_yapildi = False
if "hoca_adi" not in st.session_state:
    st.session_state.hoca_adi = ""

if not st.session_state.giris_yapildi:
    st.markdown("""
    <div class="login-wrap">
        <div class="login-logo">📊</div>
        <div class="login-title">Optik Notlandırma</div>
        <div class="login-sub">Sisteme giriş yapın</div>
    </div>
    """, unsafe_allow_html=True)

    # Formu ortala
    _, col_mid, _ = st.columns([1, 2, 1])
    with col_mid:
        hoca_input   = st.text_input("Adınız Soyadınız", placeholder="Öğr. Gör. Ad Soyad")
        kullanici    = st.text_input("Kullanıcı Adı", placeholder="kullanıcı adı")
        sifre_input  = st.text_input("Şifre", type="password", placeholder="••••••••")
        giris_btn    = st.button("Giriş Yap", use_container_width=True)

        if giris_btn:
            if kullanici == KULLANICI_ADI and sifre_dogrula(sifre_input):
                st.session_state.giris_yapildi = True
                st.session_state.hoca_adi = hoca_input.strip() or "Öğretim Görevlisi"
                st.rerun()
            else:
                st.error("❌ Kullanıcı adı veya şifre hatalı.")
    st.stop()

# ── Giriş yapıldı — normal akış devam ──────────────────────────────────────

st.markdown(f"""
<div class="hero-wrap">
  <div class="hero-badge">v2.0 · Otomatik Notlandırma</div>
  <h1 class="hero-title">Optik <span>Notlandırma</span> Sistemi</h1>
  <p class="hero-sub">TXT → Excel dönüşüm · Soru analizi · Sınıf istatistikleri</p>
  <div class="hero-credit">✦ &nbsp;<b>{st.session_state.hoca_adi}</b></div>
</div>
""", unsafe_allow_html=True)

# ── Sidebar ─────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown('<p class="step-lbl">① Cevap Anahtarı</p>', unsafe_allow_html=True)
    anahtar_input = st.text_input(
        "Cevap anahtarı",
        placeholder="örn: ABCDABCDABCD",
        label_visibility="collapsed",
    ).strip().upper()

    if anahtar_input:
        st.markdown(
            f'<div style="font-family:JetBrains Mono,monospace;font-size:0.75rem;'
            f'color:#7c6af7;margin-top:0.3rem;">'
            f'{len(anahtar_input)} soru · {round(100/len(anahtar_input),2)} pt/soru</div>',
            unsafe_allow_html=True
        )

    st.markdown('<p class="step-lbl" style="margin-top:1.5rem;">② TXT Dosyası</p>', unsafe_allow_html=True)
    yuklenen = st.file_uploader(
        "Optik okuyucu TXT",
        type=["txt"],
        label_visibility="collapsed",
    )

    st.markdown('<div style="margin-top:1.8rem"></div>', unsafe_allow_html=True)
    isle_btn = st.button("▶  Notlandır", use_container_width=True)

    st.markdown("---")
    st.markdown('<p class="step-lbl" style="margin-top:0;">③ Ders Bilgileri</p>', unsafe_allow_html=True)
    ders_adi       = st.text_input("Ders Adı",    placeholder="örn: Matematik I",   label_visibility="visible", key="ders_adi")
    ders_kodu      = st.text_input("Ders Kodu",   placeholder="örn: MAT101",        label_visibility="visible", key="ders_kodu")
    bolum          = st.text_input("Bölüm",       placeholder="örn: Bilgisayar Müh.",label_visibility="visible", key="bolum")
    donem          = st.selectbox("Dönem", ["Güz", "Bahar", "Yaz"], key="donem")
    akademik_yil   = st.text_input("Akademik Yıl", placeholder="2024-2025",         label_visibility="visible", key="akademik_yil")

    st.markdown("---")
    st.markdown("""
    <div style="font-size:0.72rem;color:#4a4860;line-height:1.8;">
    <b style="color:#6b6880;">Desteklenen Formatlar</b><br>
    <span style="color:#7c6af7;">A</span> TC+OgrNo+Cep bitişik<br>
    <span style="color:#7c6af7;">B</span> TC+OgrNo bitişik<br>
    <span style="color:#7c6af7;">C</span> Boşlukla ayrılmış<br><br>
    ÇAP öğrencisi: OgrNo başında C
    </div>
    """, unsafe_allow_html=True)
    st.markdown("---")
    if st.button("🚪 Çıkış Yap", use_container_width=True):
        st.session_state.giris_yapildi = False
        st.session_state.hoca_adi = ""
        st.rerun()

# ── Ana içerik ───────────────────────────────────────────────────────────────
if not isle_btn:
    tab_format, tab_excel, tab_kilavuz = st.tabs(["📌 TXT Formatı", "📊 Excel Çıktısı", "📖 Kullanım Kılavuzu"])
    with tab_format:
        st.markdown("""
        <div class="kilavuz-wrap">
        <div style="font-size:0.7rem;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:var(--text3);margin-bottom:1rem;">Desteklenen TXT Formatları</div>
        <div style="font-family:'JetBrains Mono',monospace;font-size:0.8rem;color:var(--text3);line-height:2.3;">
            <span style="color:#7c6af7;font-weight:700;">Format A</span> — TC + OgrNo + Cep bitişik (29-30 hane)<br>
            <span style="background:var(--bg3);padding:0.1rem 0.5rem;border-radius:4px;color:var(--text);">YILMAZ MEHMET 12345678901<b style="color:#a89ef9;">12345678</b><b style="color:#34d399;">5554443322</b> CAED…</span><br><br>
            <span style="color:#7c6af7;font-weight:700;">Format B</span> — TC + OgrNo bitişik, Cep yok (19 hane)<br>
            <span style="background:var(--bg3);padding:0.1rem 0.5rem;border-radius:4px;color:var(--text);">YILMAZ MEHMET 1234567890112345678 AAAD…</span><br><br>
            <span style="color:#7c6af7;font-weight:700;">Format C</span> — Boşlukla ayrılmış (klasik format)<br>
            <span style="background:var(--bg3);padding:0.1rem 0.5rem;border-radius:4px;color:var(--text);">YILMAZ MEHMET 12345678901 12345678 ABCD…</span><br><br>
            <span style="color:var(--text3);font-size:0.75rem;">ÇAP öğrencisi: Öğrenci numarası başında C harfi olabilir (örn: C12345678)</span>
        </div>
        </div>
        """, unsafe_allow_html=True)

    with tab_excel:
        st.markdown("""
        <div class="kilavuz-wrap">
        <div style="font-size:0.7rem;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:var(--text3);margin-bottom:1rem;">Excel Çıktısı — 6 Sheet</div>
        <div style="font-size:0.85rem;color:var(--text3);line-height:2.5;">
            <span style="color:#7c6af7;font-size:1rem;">①</span> <b style="color:#7c6af7;">Proliz Not Girişi</b> — Öğrenci No + her soru puanı (Proliz sistemine yüklenebilir format)<br>
            <span style="color:#7c6af7;font-size:1rem;">②</span> <b style="color:#7c6af7;">Detaylı Liste</b> — TC · Cep · Toplam Puan · Başarı Durumu · Tüm soru puanları<br>
            <span style="color:#34d399;font-size:1rem;">③</span> <b style="color:#34d399;">Özet</b> — Ad Soyad · TC · Toplam · Geçti/Kaldı hızlı bakış<br>
            <span style="color:#f59e0b;font-size:1rem;">④</span> <b style="color:#f59e0b;">Soru Analizi</b> — Doğru oranı · Zorluk seviyesi · Renk kodlu<br>
            <span style="color:#f59e0b;font-size:1rem;">⑤</span> <b style="color:#f59e0b;">İstatistik</b> — Ortalama · Std. Sapma · Medyan · Min/Max · Cevap Anahtarı<br>
            <span style="color:var(--text3);font-size:1rem;">⑥</span> <b style="color:var(--text2);">Ham TXT</b> — Her satırın ham cevap dizisi (hata ayıklama için)<br><br>
            <span style="color:#34d399;">↑</span> Tüm öğrenci listeleri öğrenci numarasına göre otomatik sıralanır
        </div>
        </div>
        """, unsafe_allow_html=True)

    with tab_kilavuz:
        st.markdown("""
        <div class="kilavuz-wrap">
        <div style="font-size:0.7rem;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:var(--text3);margin-bottom:1.2rem;">Adım Adım Kullanım Kılavuzu</div>

        <div class="kilavuz-step">
            <div class="kilavuz-num">1</div>
            <div class="kilavuz-content">
                <b>Cevap Anahtarını Girin</b>
                <p>Sol paneldeki "Cevap Anahtarı" alanına sınav cevaplarını büyük harfle girin.<br>
                Örnek: ABCDABCDABCD (boşluksuz, sadece A-E arası harfler)</p>
                <div class="kilavuz-code">örn: ABCDEABCDEABCDE → 15 soruluk sınav</div>
            </div>
        </div>

        <div class="kilavuz-step">
            <div class="kilavuz-num">2</div>
            <div class="kilavuz-content">
                <b>TXT Dosyasını Yükleyin</b>
                <p>Optik okuyucudan alınan .txt uzantılı dosyayı sol panelden yükleyin.<br>
                UTF-8, CP1254 (Türkçe Windows) ve Latin-1 encoding otomatik algılanır.</p>
            </div>
        </div>

        <div class="kilavuz-step">
            <div class="kilavuz-num">3</div>
            <div class="kilavuz-content">
                <b>Ders Bilgilerini Doldurun</b>
                <p>Sol paneldeki ders bilgileri alanını doldurun. Bu bilgiler PDF rapora otomatik eklenir.<br>
                Ders adı, kodu, bölüm, dönem ve akademik yıl zorunlu değildir.</p>
            </div>
        </div>

        <div class="kilavuz-step">
            <div class="kilavuz-num">4</div>
            <div class="kilavuz-content">
                <b>Notlandır Butonuna Tıklayın</b>
                <p>▶ Notlandır butonuna tıkladığınızda sistem otomatik olarak:<br>
                Her öğrencinin cevaplarını analiz eder, doğru/yanlış/boş sayar,<br>
                100 üzerinden puanlar (100 ÷ soru sayısı × doğru sayısı).</p>
            </div>
        </div>

        <div class="kilavuz-step">
            <div class="kilavuz-num">5</div>
            <div class="kilavuz-content">
                <b>Sonuçları İndirin</b>
                <p>İşlem tamamlandığında iki seçenek sunulur:<br>
                <b style="color:#34d399;">Excel (.xlsx)</b> — 6 sayfalık detaylı çalışma kitabı<br>
                <b style="color:#f87171;">PDF (.pdf)</b> — Yazdırılabilir analiz raporu</p>
            </div>
        </div>

        <div class="kilavuz-step">
            <div class="kilavuz-num">!</div>
            <div class="kilavuz-content">
                <b>Sık Karşılaşılan Sorunlar</b>
                <p>• <b>Cevap boş görünüyor:</b> TXT dosyası doğru formatta değil, Format sekmesine bakın.<br>
                • <b>Türkçe karakter sorunu:</b> Dosyayı Windows CP1254 ile kaydedin.<br>
                • <b>Cep numarası cevaplara karışıyor:</b> Sistem 19+ haneli bloklarda cep no'yu otomatik atar.<br>
                • <b>ÇAP öğrencisi görünmüyor:</b> Öğrenci no'sunun C ile başladığını kontrol edin.</p>
            </div>
        </div>

        </div>
        """, unsafe_allow_html=True)

elif not anahtar_input:
    st.warning("⚠️ Lütfen sol panelden cevap anahtarını girin.")
elif not yuklenen:
    st.warning("⚠️ Lütfen sol panelden bir TXT dosyası yükleyin.")
else:
    try:
        raw = yuklenen.read()
        metin = None
        for enc in ("utf-8", "cp1254", "latin-1"):
            try:
                metin = raw.decode(enc)
                break
            except UnicodeDecodeError:
                continue
        if metin is None:
            st.error("Dosya okunamadı.")
            st.stop()
    except Exception as e:
        st.error(f"Dosya okunamadı: {e}")
        st.stop()

    with st.spinner("İşleniyor…"):
        sonuclar, hatalar = isle(metin, anahtar_input)

    if not sonuclar:
        st.error("Hiç öğrenci verisi işlenemedi. Dosya formatını kontrol edin.")
        st.stop()

    # ── Metrik kartları ──────────────────────────────────────────────────────
    toplamlar   = [r["toplam"] for r in sonuclar]
    soru_sayisi = len(anahtar_input)
    ort         = np.mean(toplamlar)
    std         = np.std(toplamlar)
    gecme       = sum(1 for t in toplamlar if t >= 50)
    en_yuksek   = max(toplamlar)

    st.markdown(f"""
    <div class="metric-grid">
        <div class="mc purple">
            <div class="mc-label">Öğrenci</div>
            <div class="mc-val">{len(sonuclar)}</div>
            <div class="mc-sub">{soru_sayisi} soru · {round(100/soru_sayisi,2)} pt/soru</div>
        </div>
        <div class="mc green">
            <div class="mc-label">Sınıf Ortalaması</div>
            <div class="mc-val">{ort:.1f}</div>
            <div class="mc-sub">100 üzerinden</div>
        </div>
        <div class="mc sky">
            <div class="mc-label">Standart Sapma</div>
            <div class="mc-val">{std:.1f}</div>
            <div class="mc-sub">Dağılım genişliği</div>
        </div>
        <div class="mc amber">
            <div class="mc-label">Geçen (≥50)</div>
            <div class="mc-val">{gecme}</div>
            <div class="mc-sub">%{round(gecme/len(sonuclar)*100,1)} geçme oranı</div>
        </div>
        <div class="mc rose">
            <div class="mc-label">En Yüksek Puan</div>
            <div class="mc-val">{en_yuksek:.1f}</div>
            <div class="mc-sub">En düşük: {min(toplamlar):.1f}</div>
        </div>
    </div>
    """, unsafe_allow_html=True)

    # ── Hatalar ─────────────────────────────────────────────────────────────
    if hatalar:
        with st.expander(f"⚠️ {len(hatalar)} satırda sorun tespit edildi", expanded=False):
            for h in hatalar:
                st.markdown(f'<div class="warn-box">{h}</div>', unsafe_allow_html=True)

    # ── Puan Dağılımı ────────────────────────────────────────────────────────
    st.markdown('<div class="sec-head">📈 Puan Dağılımı</div>', unsafe_allow_html=True)

    araliklar = [
        ("0–24",  0,  24,  "#f87171"),
        ("25–49", 25, 49,  "#fb923c"),
        ("50–64", 50, 64,  "#fbbf24"),
        ("65–79", 65, 79,  "#34d399"),
        ("80–89", 80, 89,  "#22d3ee"),
        ("90–100",90, 100, "#7c6af7"),
    ]
    dagilim_html = '<div class="dist-bar-wrap">'
    max_cnt = 1
    cnts = []
    for lbl, lo, hi, color in araliklar:
        cnt = sum(1 for t in toplamlar if lo <= t <= hi)
        cnts.append(cnt)
        if cnt > max_cnt:
            max_cnt = cnt

    for (lbl, lo, hi, color), cnt in zip(araliklar, cnts):
        pct_bar = round(cnt / max_cnt * 100)
        dagilim_html += f"""
        <div class="dist-row">
            <div class="dist-lbl">{lbl}</div>
            <div class="dist-bar-bg">
                <div class="dist-bar-fill" style="width:{pct_bar}%;background:{color};">
                    <span>{'%'+str(round(cnt/len(toplamlar)*100,1)) if cnt else ''}</span>
                </div>
            </div>
            <div class="dist-cnt">{cnt}</div>
        </div>"""
    dagilim_html += '</div>'
    st.markdown(dagilim_html, unsafe_allow_html=True)

    # ── Soru Analizi ─────────────────────────────────────────────────────────
    st.markdown('<div class="sec-head">🔍 Soru Analizi</div>', unsafe_allow_html=True)

    analiz = soru_analizi_hesapla(sonuclar, anahtar_input)

    st.markdown("""
    <div style="display:flex;gap:1.2rem;margin-bottom:0.7rem;font-size:0.75rem;color:#6b6880;">
        <span><span style="color:#34d399;font-weight:700;">■</span> Kolay ≥70%</span>
        <span><span style="color:#fbbf24;font-weight:700;">■</span> Orta 40-69%</span>
        <span><span style="color:#f87171;font-weight:700;">■</span> Zor &lt;40%</span>
    </div>
    """, unsafe_allow_html=True)

    cards_html = '<div class="qa-grid">'
    for a in analiz:
        cls = "easy" if a["pct"] >= 70 else ("mid" if a["pct"] >= 40 else "hard")
        cards_html += f"""
        <div class="qa-card {cls}">
            <div class="q-no">S{a['soru']}</div>
            <div class="q-pct">%{a['pct']:.0f}</div>
            <div class="q-ans">{a['anahtar']}</div>
        </div>"""
    cards_html += '</div>'
    st.markdown(cards_html, unsafe_allow_html=True)

    # Detaylı tablo
    with st.expander("📋 Soru Analizi Detayları", expanded=False):
        df_analiz_ui = pd.DataFrame([{
            "Soru": f"S{a['soru']}",
            "Anahtar": a["anahtar"],
            "Doğru": a["dogru"],
            "Yanlış": a["yanlis"],
            "Boş": a["bos"],
            "Doğru %": a["pct"],
            "Zorluk": "🟢 Kolay" if a["pct"] >= 70 else ("🟡 Orta" if a["pct"] >= 40 else "🔴 Zor"),
        } for a in analiz])
        st.dataframe(df_analiz_ui, use_container_width=True, hide_index=True,
                     column_config={
                         "Doğru %": st.column_config.ProgressColumn(
                             "Doğru %", min_value=0, max_value=100, format="%.1f%%"
                         )
                     })

    # ── Önizleme Tablosu ─────────────────────────────────────────────────────
    st.markdown('<div class="sec-head">📋 Önizleme Tablosu</div>', unsafe_allow_html=True)

    def ogr_sort_key(r):
        ogr = r["ogr_no"]
        num = re.sub(r'[^0-9]', '', ogr)
        return (ogr.startswith('C'), int(num) if num else 0)

    sonuclar_sirali_ui = sorted(sonuclar, key=ogr_sort_key)

    df_oniz = pd.DataFrame([{
        "#":             idx,
        "Öğrenci No":    r["ogr_no"],
        "Ad Soyad":      r["ad_soyad"],
        "TC":            r["tc"],
        "Cep":           r["cep"] if r["cep"] else "—",
        "Toplam (100)":  r["toplam"],
        "Durum":         "✓ Geçti" if r["toplam"] >= 50 else "✗ Kaldı",
    } for idx, r in enumerate(sonuclar_sirali_ui, 1)])

    st.dataframe(
        df_oniz,
        use_container_width=True,
        hide_index=True,
        column_config={
            "#":          st.column_config.NumberColumn("#",         width="small"),
            "Öğrenci No": st.column_config.TextColumn("Öğrenci No", width="medium"),
            "Ad Soyad":   st.column_config.TextColumn("Ad Soyad",   width="large"),
            "TC":         st.column_config.TextColumn("TC No",       width="medium"),
            "Cep":        st.column_config.TextColumn("Cep Tel",     width="medium"),
            "Toplam (100)": st.column_config.ProgressColumn(
                "Toplam Puan", min_value=0, max_value=100, format="%.2f"
            ),
            "Durum": st.column_config.TextColumn("Durum", width="small"),
        }
    )

    # ── İndirme ──────────────────────────────────────────────────────────────
    st.markdown("---")

    # Her iki dosyayı butonlar render edilmeden ÖNCE oluştur.
    # Böylece download_button tıklanması sayfayı yeniden çizmez ve
    # diğer buton kaybolmaz.
    with st.spinner("Excel ve PDF hazırlanıyor…"):
        excel_buf = excel_olustur(sonuclar, anahtar_input)
        ders_bilgisi = {
            "ders_adi":     st.session_state.get("ders_adi", ""),
            "ders_kodu":    st.session_state.get("ders_kodu", ""),
            "bolum":        st.session_state.get("bolum", ""),
            "donem":        st.session_state.get("donem", ""),
            "akademik_yil": st.session_state.get("akademik_yil", ""),
        }
        pdf_buf = pdf_olustur(
            sonuclar, anahtar_input,
            dosya_adi=yuklenen.name.rsplit(".", 1)[0],
            ders_bilgisi=ders_bilgisi,
            hoca_adi=st.session_state.get("hoca_adi", ""),
        )

    cepli = sum(1 for r in sonuclar if r.get("cep"))
    st.markdown(
        f'<div class="ok-box">✅ Hazır · 6 sheet · {len(sonuclar)} öğrenci · '
        f'{gecme} geçti · {cepli} cep numarası tespit edildi</div>',
        unsafe_allow_html=True
    )

    col_dl1, col_dl2, _ = st.columns([2, 2, 3])
    with col_dl1:
        st.download_button(
            label="⬇️  Excel İndir  (.xlsx)",
            data=excel_buf,
            file_name=yuklenen.name.rsplit(".", 1)[0] + "_sonuclar.xlsx",
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            use_container_width=True,
        )
    with col_dl2:
        st.download_button(
            label="⬇️  PDF İndir  (.pdf)",
            data=pdf_buf,
            file_name=yuklenen.name.rsplit(".", 1)[0] + "_rapor.pdf",
            mime="application/pdf",
            use_container_width=True,
        )

# ── Footer ────────────────────────────────────────────────────────────────────
st.markdown("""
<div class="footer-bar">
    Optik Notlandırma Sistemi &nbsp;·&nbsp; v2.0<br>
    <b>Öğr. Gör. Hatice Tekiş</b> tarafından geliştirilmiştir
</div>
""", unsafe_allow_html=True)
